//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCodingC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userProject
    {
        public int userID { get; set; }
        public int projectID { get; set; }
        public byte[] isActive { get; set; }
        public System.DateTime assignedDate { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Users Users { get; set; }
    }
}
